insert into department (name)
values
  ('Sales'),
  ('Legal'),
  ('Engineering'),
  ('Finance');

insert into role (title, salary, department_id)
values
  ('Sales Manager', '100000.00', 1),
  ('Engineering Manager', '250000.00', 3),
  ('Finance Manager', '150000.00', 4),
  ('Software Engineer', '90000.00', 3),
  ('Lawyer', '200000.00', 2),
  ('Sales Engineer', '60000.00', 1),
  ('Analyst', '70000.00', 4);


insert into employee (first_name, last_name, role_id, manager_id)
values
  ('Ronald', 'Firbank', 1, NULL),
  ('Virginia', 'Woolf', 2, NULL),
  ('Piers', 'Gaveston', 3, NULL),
  ('Charles', 'LeRoi', 5, NULL),
  ('Katherine', 'Mansfield', 5, NULL),
  ('Dora', 'Carrington', 4, 2),
  ('Edward', 'Bellamy', 7, 3),
  ('Montague', 'Summers', 6, 1),
  ('Octavia', 'Butler', 6, 1),
  ('Unica', 'Zurn', 4, 2),
  ('James', 'Fraser', 7, 3),
  ('Jack', 'London', 6, 1),
  ('Robert', 'Bruce', 6, 1),
  ('Peter', 'Greenaway', 6, 1),
  ('Derek', 'Jarman', 7, 3),
  ('Paolo', 'Pasolini', 7, 3),
  ('Heathcote', 'Williams', 4, 2),
  ('Sandy', 'Powell', 4, 2),
  ('Emil', 'Zola', 4, 2),
  ('Sissy', 'Coalpits', 7, 3),
  ('Antoinette', 'Capet', 7, 3),
  ('Samuel', 'Delany', 7, 3),
  ('Tony', 'Duvert', 7, 3),
  ('Dennis', 'Cooper', 7, 3),
  ('Monica', 'Bellucci', 7, 3),
  ('Samuel', 'Johnson', 4, 2),
  ('John', 'Dryden', 7, 3),
  ('Alexander', 'Pope', 7, 3),
  ('Lionel', 'Johnson', 7, 3),
  ('Aubrey', 'Beardsley', 4, 2),
  ('Tulse', 'Luper', 6, 1),
  ('William', 'Morris', 7, 3),
  ('George', 'Shaw', 6, 1),
  ('Arnold', 'Bennett', 6, 1),
  ('Algernon', 'Blackwood', 4, 2),
  ('Rhoda', 'Broughton', 7, 3),
  ('Hart', 'Crane', 7, 3),
  ('Vitorio', 'DeSica', 7, 3),
  ('Wilkie', 'Collins', 7, 3),
  ('Elizabeth', 'Gaskell', 4, 2),
  ('George', 'Sand', 7, 3),
  ('Vernon', 'Lee', 4, 2),
  ('Arthur', 'Machen', 6, 1),
  ('Frederick', 'Marryat', 6, 1),
  ('Harriet', 'Martineau', 6, 1),
  ('George', 'Meredith', 6, 1),
  ('Margaret', 'Oliphant', 4, 2),
  ('Anthony', 'Trollope', 6, 1),
  ('Charlotte', 'Yonge', 6, 1),
  ('Horace', 'Walpole', 6, 1),
  ('Matthew', 'Lewis', 6, 1),
  ('William', 'Bedford', 4, 2),
  ('Anne', 'Radcliffe', 6, 1),
  ('Charles', 'Brown', 6, 1),
  ('Eliza', 'Parsons', 7, 3),
  ('Susan', 'Hill', 7, 3),
  ('Sydney', 'Owenson', 7, 3),
  ('Hubert', 'Crackanthorpe', 7, 3),
  ('William', 'Carleton', 7, 3),
  ('Gerald', 'Griffin', 4, 2);